### PR TITLE
GDI library refactoring, DirectFB UI fix

### PR DESCRIPTION
**Pull request by awakecoding**
This third round of refactoring includes libfreerdp-gdi modifications for non-conflicting use on Windows, along with some fixes for the DirectFB UI.

### CODE REVIEW

**Comment by awakecoding** [comment]
Before merging this pull request, there would be a couple of things to notice:

I removed the inline keyword from libfreerdp-rfx, it'll need to be changed to a macro instead. Windows port currently has a linked error with libfreerdp-rfx and I don't know exactly how I'm going to fix that. Windows does not export methods by default, and it acts really weird when you want to export methods from a static library instead of a dynamic library. Any help on that is appreciated. Besides the currently unstable Windows port, nothing particularly dangerous. I could revert some of the latest changes in the Windows port so that we could merge this.

**Comment by awakecoding** [comment]
Ok, I have stabilized the stuff contained in this pull request (it was mostly the Windows port). The rest should in theory be stable enough. I have restored the inline of one function in libfreerdp-rfx, and replace the other one with a macro (should be faster than inlining anyway).

**Comment by g-reno** [comment]
About the --gdi switch.

Maybe it should be defaulted to hardware and the code should check for hardware and if not there then do a fallback to software.  That would work on all installations.

**Comment by awakecoding** [comment]
@g-reno: at this point, it's just a matter of choosing a particular implementation, where the system required for them is always available. In xfreerdp, both implementations are available, the X11-specific one, and the software-only implementation. For dfbfreerdp, only a software implementation is currently available, and we'd expect some improvements in the future where a DirectFB-specific implementation will be added. "hardware" in this case only means usage of the library-specific API, which can make use of 2D acceleration, not 3D acceleration. Just having the switch in the DirectFB UI will make it tremendously easier for someone to implement a better GDI implementation that can take advantage of 2D acceleration, while being able to switch between the two implementations for comparison and verification of the correctness of the implementation.

**Comment by otavio** [comment]
@awakecoding Your commit messages are again longer the expected. Please rebase and fix those since it is going to be worse and worse. For a project we want to attract more people to contribute those guidelines and policies makes sharing the work and learning curve easier.

**Comment by awakecoding** [comment]
@otavio: got any tips or information on how to clean up older commit messages to replace them with something more meaningful and descriptive? I don't mind cleaning up after myself, I just never did it before with git

**Comment by otavio** [comment]
@awakecoding sure. You can use:

```
git rebase -i origin/master
```

This using the edit function.

You can read more about it at http://book.git-scm.com/4_interactive_rebasing.html

**Comment by g-reno** [comment]
I've found that rebase can destroy your commit history if you're not careful.

It happened to me where I had the rebase commit and then lost the history that made up the merging branch.

Proceed cautiously.

**Comment by otavio** [comment]
Yes; rebase is a powerful tool but you need to not  change already public commits. GIT is an awesome tool but has potential to blow stuff out if wrong used.

**Comment by otavio** [comment]
You can compare git rebase to mkfs ;-)

**Comment by g-reno** [comment]
Yep.  

When you rebase you then have unreachable objects since you rebased everything to the main branch.  

And if you run git-gc to clean things up then you lose those and the commit history.

**Comment by otavio** [comment]
If you use it for unpublished branches this is all safe and good. Besides you can do a branch backup before doing the rebase... as:

```
git branch backup-my-pet-branch
git rebase -i origin/master
```

After it is all OK and checked, you do:

```
git branch -D backup-my-pet-branch
```

So no risk to lose data.

**Comment by awakecoding** [comment]
@otavio: when using git commit, I add the message using the -m option. Is shortlog something any different? Was the problem just the fact that I made a multi-line comment which doesn't look good in shortlog? Is there any way to provide a short comment, and a long detailed comment for a particular commit? I'm learning new stuff here regarding git

**Comment by otavio** [comment]
Yes, you did it wrong ... this ought to look as:

```
shortlog
<empty line>
long description
```

As:

```
rfx: refactor foo allocation method

We used to use a stupid method to allocate foo and now we
started to use a cleaver one that avoid redoing it all the time
and thus reducing the footprint of overwall memory usage.
```

Got it?

**Comment by awakecoding** [comment]
@otavio: if I understand you correctly, I should format my comments this way:

< component name >: < short description >
< empty line>
< long
...
...
description>

I made my multi-line comment using SmartGit, how do I go about inserting new lines when using the command line git client? Do I simply use \n?

**Comment by otavio** [comment]
I usually do:

```
git commit
```

And then it opens an editor windows which I use to type the commit log. I don't do multi-line comments directly on command line.

**Comment by awakecoding** [comment]
@otavio: I just tried using git commit --amend on a couple of older commits, but when I try to push it simply says everything up to date and does not push the amended commits. I tried with -f, no difference. What should I do? Is interactive rebase the best option?

**Comment by otavio** [comment]
You can use rebase until those commits are made into real public/official repository.

You can check it comparing it against freerdp remote... here for example I have two remotes into my tree:
- freerdp
- ossystems

So I check if those are made public checking as:

```
 git shortlog freerdp/master..
```

If the commits I wish to change shows up I am safe and I can do the rebase. After I do them I usually do:

```
 git push -f ossystems master
```

To put them into our remote. Since they're are not available onto freerdp remote you will be able to push them to freerdp remote doing:

```
 git push freerdp master
```

**Pull request merged**
